version: '3.1'

services:

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: dockerrocks!
      POSTGRES_DB: journal

    ports:
      - "5432:5432"