app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/is590db
    username: docker
    password: dockerrocks!
    pool-size: 30

#app:
#  datasource:
#    jdbc-url: jdbc:postgresql://localhost:5432/is590db
#    username: userPostgres
#    password: passwordPostgres
#    pool-size: 30

#app:
#  datasource:
#    jdbc-url: jdbc:postgresql://is590rdb.cwqe0hexexyg.us-west-2.rds.amazonaws.com:5432/is590db
#    username: docker
#    password: dockerrocks!
#    pool-size: 30