app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/journal
    username: docker
    password: dockerrocks!
    pool-size: 30
  jwt:
    secretKey: "Our Super Secret Test Key which will get overridden"
    tokenPrefix: "Bearer "
    tokenExpirationAfterDays: 10